### PR TITLE
Generate docs for 3.1

### PR DESCRIPTION
**Pull request by andrehjr**
✨ 

Generated the docs, and it seems to working fine for me :) 
```ruby
[3] pry(main)> ? Class#subclasses

From: class.c (C Method):
Owner: Class
Visibility: public
Signature: subclasses()
Number of lines: 18

Returns an array of classes where the receiver is the
direct superclass of the class, excluding singleton classes.
The order of the returned array is not defined.

   class A; end
   class B < A; end
   class C < B; end
   class D < A; end

   A.subclasses        #=> [D, B]
   B.subclasses        #=> [C]
   C.subclasses        #=> []

VALUE
rb_class_subclasses(VALUE klass)
{
    return class_descendants(klass, true);
}


[4] pry(main)> ? Enumerable#compact

From: enum.c (C Method):
Owner: Enumerable
Visibility: public
Signature: compact()
Number of lines: 15

Returns an array of all non-nil elements:

  a = [nil, 0, nil, 'a', false, nil, false, nil, 'a', nil, 0, nil]
  a.compact # => [0, "a", false, false, "a", 0]

static VALUE
enum_compact(VALUE obj)
{
    VALUE ary;

    ary = rb_ary_new();
    rb_block_call(obj, id_each, 0, 0, compact_i, ary);

    return ary;
}
```

### CODE REVIEW

**Comment by kyrylo** [comment]
👍

**Comment by miharekar** [comment]
Can this get released, please? 🙏

**Comment by andrehjr** [comment]
Hi @kyrylo, Happy new year 🙌 

Can you release a new version? Or can I do it?

**Comment by kyrylo** [comment]
@andrehjr Happy New Year!

Just released v1.3.0, thanks!

**Pull request merged**
