### PR TITLE
Generate docs for Ruby 2.3

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by kyrylo** [comment]
It is useful to have this, but we won't be able to release the plugin because the build needs to be fixed first.

**Comment by yui-knk** [comment]
Build was fixed now 😈

**Comment by kyrylo** [comment]
Oops, please rebase.

**Comment by yui-knk** [comment]
Rebased. But CI did not start...

**Comment by kyrylo** [comment]
Looks like it was disabled: https://travis-ci.org/profile/pry
I don't have the rights to enable that. /cc @banister

**Comment by kyrylo** [comment]
@yui-knk hey, could you force push to trigger a build? Looks like @banister fixed it.

**Comment by yui-knk** [comment]
OK. CI starts to run 😍

**Comment by kyrylo** [comment]
🍏  superfantastic

**Comment by yui-knk** [comment]
👍

**Pull request merged**
