### PR TITLE
Generate docs for Ruby 2.5.0

### PR DESCRIPTION
**Pull request by k-ta-yamada**
I am aware that you are commenting "It is necessary to introduce Ruby 2.5 compatibility" at pull request #74, but it is inconvenient not to use pry-doc while waiting for it, so I tried pull request It was.

This sentence is created using google translation.
I am sorry if there are unclear points.

### CODE REVIEW

**Comment by kyrylo** [comment]
Missed this release 👍

**Comment by k-ta-yamada** [comment]
Thank you for the merge.
I am looking forward to the release.

**Comment by kyrylo** [comment]
Looks like there's an issue to fix https://travis-ci.org/pry/pry-doc/jobs/325325827

I don't have time to dig into it, but shouldn't be too hard. You can use the master branch for now. Releasing broken pry-doc is not an option :P

**Comment by k-ta-yamada** [comment]
That issue also occurred in my environment.
I will try to fix, but my skills may be insufficient.
Anyway, I will challenge for a while.

**Comment by k-ta-yamada** [comment]
I created a new pull request #77 😃

**Pull request merged**
