### PR TITLE
fix test failure in Ruby 2.5

### PR DESCRIPTION
**Pull request by k-ta-yamada**
Fixed, tests began to pass.
I am not confident, but please review whether there is no problem.

### CODE REVIEW

**Comment by kyrylo** [comment]
Sorry, I'm afraid I don't understand what this does and what was broken in the first place. Perhaps, adding a test would clarify why this fix is correct?

**Comment by k-ta-yamada** [comment]
@kyrylo, Thank you for review.
I do not know whether I can successfully write the test, so I will try to explain the correction this time.

---

From Ruby 2.5 it seems that the `puts` method appears as singleton method in Method class.

```rb
2.4.0 pry(main)> method (:puts)
=> #<Method: Object(Kernel)#puts>
```

```rb
2.5.0 pry(main)> method(:puts)
=> #<Method: main.puts>
```

So, in 2.4 we were able to return the result in the first `YARD::Registry.at` of `registry_lookup` method, but in 2.5 it will be `nil`.

```rb
2.4.0 pry(main)> meth = method (:puts)
=> #<Method: Object(Kernel)#puts>
2.4.0 pry(main)> YARD::Registry.at(Pry::MethodInfo.send(:receiver_notation_for, meth))
=> #<yardoc method Kernel#puts>
```

```rb
2.5.0 pry(main)> meth = method (:puts)
=> #<Method: main.puts>
2.5.0 pry(main)> YARD::Registry.at(Pry::MethodInfo.send(:receiver_notation_for, meth))
=> nil
```

And until it reaches the condition of `meth.owner == Kernel`, `puts` is a method of Kernel, `YARD::Registry.at (" Object ## {meth.name} ")` is nil and It was getting.

```rb
2.5.0 pry(main)> YARD::Registry.at("Object##{meth.name}")
=> nil
```

By the way it is also nil if it is 2.4.

```rb
2.4.0 pry(main)> YARD::Registry.at("Object##{meth.name}")
=> nil
```

I simply added the following, is it inappropriate?

```rb
2.5.0 pry(main)> YARD::Registry.at("Kernel##{meth.name}")
=> #<yardoc method Kernel#puts>
```

**Comment by banister** [comment]
Thanks @k-ta-yamada great work :tada:

**Comment by kyrylo** [comment]
👍

**Comment by k-ta-yamada** [comment]
@banister @kyrylo Thank you for the merge and release 👍

**Pull request merged**
